apiVersion: v1
kind: Service
metadata:
  name: qa-karanteenissa-fi-front-svc
  namespace: qa
spec:
  selector:
    app: qa-karanteenissa-fi-front
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80